pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 30
  reconnect: true
  host: localhost

development:
  <<: *pg
  database: store_development

test:
  <<: *pg
  database: store_test

production:
  <<: *pg
  database: store_prod
